# Generated by Django 4.1.7 on 2023-04-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomDeveloperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DevName', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('github_link', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('institute1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('degree1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('duration1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('result1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('institute2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('degree2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('duration2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('result2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('company1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('position1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('start1', models.DateTimeField(blank=True, null=True)),
                ('end1', models.DateTimeField(blank=True, null=True)),
                ('company2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('position2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('start2', models.DateTimeField(blank=True, null=True)),
                ('end2', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
