# Generated by Django 4.1.7 on 2023-04-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerdata',
            name='end1',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='developerdata',
            name='end2',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='developerdata',
            name='start1',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='developerdata',
            name='start2',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
