# Generated by Django 4.1.7 on 2023-04-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_developerdata_activities1_developerdata_activities2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerdata',
            name='image_file',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
