# Generated by Django 4.1.7 on 2023-04-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_developerdata_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerdata',
            name='job_form_cv',
            field=models.FileField(blank=True, default=None, null=True, upload_to='CV/'),
        ),
    ]
