# Generated by Django 4.1.7 on 2023-04-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_developerdata_job_form_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('company_name', models.CharField(max_length=200)),
                ('company_location', models.CharField(max_length=200)),
                ('job_type', models.CharField(blank=True, max_length=200, null=True)),
                ('num_of_employees', models.IntegerField(blank=True, null=True)),
                ('company_description', models.TextField(blank=True, max_length=200, null=True)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=20)),
                ('role_obj1', models.CharField(blank=True, max_length=200, null=True)),
                ('role_obj2', models.CharField(blank=True, max_length=200, null=True)),
                ('role_obj3', models.CharField(blank=True, max_length=200, null=True)),
                ('role_obj4', models.CharField(blank=True, max_length=200, null=True)),
                ('role_obj5', models.CharField(blank=True, max_length=200, null=True)),
                ('role_obj6', models.CharField(blank=True, max_length=200, null=True)),
                ('role_obj7', models.CharField(blank=True, max_length=200, null=True)),
                ('role_obj8', models.CharField(blank=True, max_length=200, null=True)),
                ('role_obj9', models.CharField(blank=True, max_length=200, null=True)),
                ('role_obj10', models.CharField(blank=True, max_length=200, null=True)),
                ('job_skills1', models.CharField(blank=True, max_length=200, null=True)),
                ('job_skills2', models.CharField(blank=True, max_length=200, null=True)),
                ('job_skills3', models.CharField(blank=True, max_length=200, null=True)),
                ('job_skills4', models.CharField(blank=True, max_length=200, null=True)),
                ('job_skills5', models.CharField(blank=True, max_length=200, null=True)),
                ('job_skills6', models.CharField(blank=True, max_length=200, null=True)),
                ('job_skills7', models.CharField(blank=True, max_length=200, null=True)),
                ('job_skills8', models.CharField(blank=True, max_length=200, null=True)),
                ('job_skills9', models.CharField(blank=True, max_length=200, null=True)),
                ('job_skills10', models.CharField(blank=True, max_length=200, null=True)),
                ('min_qua', models.TextField(blank=True, max_length=200, null=True)),
                ('pref_qua', models.TextField(blank=True, max_length=200, null=True)),
                ('salary_range', models.TextField(blank=True, max_length=200, null=True)),
                ('benefits', models.TextField(blank=True, max_length=200, null=True)),
                ('circular', models.FileField(blank=True, default=None, null=True, upload_to='Circular/')),
            ],
        ),
    ]
